# Generated by Django 4.1.2 on 2022-11-08 05:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("map", "0002_cars_delete_car"),
    ]

    operations = [
        migrations.CreateModel(
            name="Car",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("TimeStamp", models.CharField(max_length=100)),
                ("Latitude", models.CharField(max_length=100)),
                ("Longitude", models.CharField(max_length=100)),
                ("CarName", models.CharField(max_length=100)),
                ("CarSpeed", models.CharField(max_length=100)),
                ("Heading", models.CharField(max_length=100)),
            ],
            options={"ordering": ["CarName"],},
        ),
        migrations.DeleteModel(name="Cars",),
    ]
